language: java
jdk:
- oraclejdk8
- oraclejdk9
- openjdk8
- openjdk9
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file_glob: true
  file: build/distributions/pdfutils*.zip
  skip_cleanup: true
  on:
    tags: true
