# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  # any push or pull request
  push:
  pull_request:


concurrency:
  group: ${{ github.ref }}-gradle
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 8, 11, 17 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up  ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@9ba54b687bf0f59b62abbf91e0d60de082e8ebc4
      - name: Build with Gradle
        uses: gradle/gradle-build-action@04b20c065cf1ab708c96e64a8811018d0a1fbc88
        env:
          SPRING_PROFILES_ACTIVE: test
        with:
          arguments: build --info
